### ISSUE TITLE
starry night

### ISSUE THREAD

**Issue by GauriRithwik** [ambilyks/Rainbow-poem-Ambily#6]
include some about starry night

**Comment by ambilyks** [comment]
fixes 766e683cb9767dbaa6a053517b0fb0c2214a57c9

**Comment by ambilyks** [comment]
fixes 766e683cb9767dbaa6a053517b0fb0c2214a57c9
#6

**Comment by ambilyks** [comment]
fixes #6

**Comment by GauriRithwik** [comment]
said about stars
